### ISSUE TITLE
想问一下摄像头视角数据的来源！

### ISSUE THREAD

**Issue by akhialomgir** [yuanyan3060/Arknights-Tile-Pos#5]

**Comment by satgo1546** [comment]
（我和楼主这段时间做摸鱼项目的时候也写了格子识别，用了图色识别和矩阵估计，效果果然非常捉鸡hhh 所以想请教一下~

levels.json里别的数据都能明白，就是每张图的view字段不知道从哪里获取…
以及代码中的魔法矩阵，是从asset bundle里提出来的吗？还是从il2cpp里提出来的？

**Comment by yuanyan3060** [comment]
矩阵计算的原理和数据几乎全是逆向得来的（
逆向了很久才发现view的数据在asset bundle里，哭

**Comment by satgo1546** [comment]
了解了，感谢w
