### ISSUE TITLE
Add OpenCV stuff in cpp/3rdparty to .gitignore?

### ISSUE THREAD

**Issue by horror-proton** [yuanyan3060/Arknights-Tile-Pos#8]
If one has OpenCV installed in the system already, it would be annoying if OpenCV dependency was cloned with the repo. (`git clone` command cannot exclude files)

<sub>
Assuming code here works fine even with a slightly different OpenCV version. 看上去应该不会导致依赖爆炸 (思考
</sub>

**Comment by yuanyan3060** [comment]
这个仓库里的代码只是用来演示一下这种计算方法，使用者应该根据自己的需求重写(确信)

**Comment by horror-proton** [comment]
> 这个仓库里的代码只是用来演示一下这种计算方法，使用者应该根据自己的需求重写(确信)

在写了在写了 (指新建目录)

话说这里好像没用到过什么 CV 相关的东西, 我在考虑使用 Eigen 或者更小的矩阵库 (思考
