### ISSUE TITLE
Perspective projection matrix could be simplified (?

### ISSUE THREAD

**Issue by horror-proton** [yuanyan3060/Arknights-Tile-Pos#9]
想问一下 `MatrixP` 中的 1000 和 0.3 是游戏中摄像机的真实配置吗, 如果不是, 考虑到这里只需要获得屏幕坐标, 没有裁切等操作, 用 `MatrixP` 把坐标换到完整的 NDC space 中是不必要的, 应该可以直接写成
$$\begin{bmatrix} \frac{h}{2} \cot\frac{\text{FOV}_h}{2} & & & \\\ & \frac{h}{2} \cot\frac{\text{FOV}_h}{2} \\\ & & 0 & 0 \\\ & &  -1 & 0 \end{bmatrix}$$
后面也不用再对 `view_point` 乘以 `height` 和 `width` 缩放了. 

(如果这是正确的话, 这部分应该也只是进行了简单的透视除法, 看上去所有变换都可以不使用任何矩阵库来进行, 但可能降低一些可读性) 
(~开摆, 我不想写 pr 了喵, 不过回头可能开个新 repo 尝试去重写一下~

**Comment by yuanyan3060** [comment]
1000 和 0.3 确实是游戏中摄像机的真实配置（

**Comment by yuanyan3060** [comment]
脱离矩阵库，感觉没有必要，因为有这种获取坐标需求的项目，opencv基本上算标配了。
